### ISSUE TITLE
Get rid of the dependency of GradedCategories on InfiniteLists

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CategoricalTowers#123]
This would allow to execute
```
LoadPackage( "GroupRepresentationsForCAP" );
LoadPackage( "GradedCategories" );
LoadPackage( "InternalModules" );
```
again without errors. In particular, the part of https://github.com/homalg-project/InternalModules/commit/8a8c90be8a6a64eb190afd7753930a6d92e11e08 which moves `LoadPackage( "InternalModules" );` to the top to avoid errors could be reverted.

**Comment by mohamed-barakat** [comment]
@kamalsaleh: What is a viable alternative and can we place it in a central package available to all three projects: CAP_project, HigherHomologicaAlgebra, and CategoricalTowers?

**Comment by kamalsaleh** [comment]
[Zfunctions](https://github.com/homalg-project/HigherHomologicalAlgebra/blob/master/ToolsForHigherHomologicalAlgebra/gap/ZFunctions.gi) can be used as alternative and I would say it can be placed in the **ToolsForHomalg** package.

**Comment by mohamed-barakat** [comment]
Wonderful, could you take care of this?

**Comment by kamalsaleh** [comment]
Of course, I have added this to my to-do list.
