### ISSUE TITLE
CI hanging while testing notebooks in FunctorCategories

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CategoricalTowers#248]
Since yesterday (https://github.com/homalg-project/CategoricalTowers/actions/runs/5274719367/jobs/9539462031), the CI is timing out. The hang seems to happen while testing the notebooks in FunctorCategories. I suspect this is due to a bug triggered by Julia master. I don't know why the `gap-docker-master` job did not hang yesterday, it should be based on the same Julia version as `gap-docker`. But today it also hangs. FinSetsForCAP tests notebooks but is not affected by this, so the issue has to be specific to the kind of notebooks in FunctorCategories (maybe the graphs?).

I currently do not have the time to look into this. @mohamed-barakat Could you test the notebooks in FunctorCategories with latest Julia master and try to narrow down where the hang occurs (e.g., when printing graphs)?

**Comment by zickgraf** [comment]
HigherHomologicalAlgebra is also affected: https://github.com/zickgraf/HigherHomologicalAlgebra/actions/runs/5286161078/jobs/9565329237 But in this case, `gap-docker` did not hang while `gap-docker-master` did. So probably the issue is not 100% reproducible and the fact that `gap-docker-master` succeeded multiple times in CategoricalTowers yesterday was just coincidence.

**Comment by kamalsaleh** [comment]
Running the tests locally with the current julia master also hangs by the first test of a Jupyter notebook, in my case, _FreydCategory_Qxy.ipynb_, in _ComplexesCategories_.

**Comment by zickgraf** [comment]
Thanks a lot @kamalsaleh for narrowing this down! I'm happy that this does not involve IJulia. Building on your observation, I have now bisected this to a Julia commit. Actually, already GAP.jl hangs (but not always, so probably by chance it did not show up in your tests). I have opened an issue: https://github.com/oscar-system/GAP.jl/issues/901

**Comment by mohamed-barakat** [comment]
Thank you both very much for investigating :)

**Comment by zickgraf** [comment]
This is fixed: https://github.com/oscar-system/GAP.jl/issues/901.
