### ISSUE TITLE
Using the option `range_of_HomStructure` for `ProsetAsCategory` does not work 

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CategoricalTowers#269]
`RangeCategoryOfHomomorphismStructure` is not a mutable attribute, if it is already set in

https://github.com/homalg-project/CategoricalTowers/blob/508d62c110913f41ecbfecf24b43a81b29bceec2/Locales/gap/IntervalCategory.gi#L242-L248

overwriting it does not work. This is (for example) the case for `ProsetAsCategory`.

Also, the line `not IsIntervalCategory( V )` is unexpected. Should this line filter out the `fail` case? Then I would check for `V <> fail`. If the code explicitly requires an interval category, a warning or an error should be printed when a wrong category is given.

To reproduce the problem, call `SetInfoLevel( InfoAttributes, 3 );` before loading "ComplexesCategories".

**Comment by zickgraf** [comment]
Addendum: The concrete issue when loading "ComplexesCategories" does actually not come from setting `range_of_HomStructure` but from `ProsetAsCategory` creating its own interval category internally, while `ADD_COMMON_METHODS_FOR_ENRICHMENT_OVER_INTERVAL_CATEGORY` uses the global one. However, the underlying issue is still the same.

**Comment by mohamed-barakat** [comment]
Thanks for detecting this bug. This was sloppiness: In this context, I set the range of the homomorphism structure using `ADD_COMMON_METHODS_FOR_PREORDERED_SETS` which invokes `ADD_COMMON_METHODS_FOR_ENRICHMENT_OVER_INTERVAL_CATEGORY`. I forgot that during the recent implementation of `ProsetAsCategory`. I improved/fixed `ADD_COMMON_METHODS_FOR_ENRICHMENT_OVER_INTERVAL_CATEGORY` following your suggestions.

**Comment by zickgraf** [comment]
https://github.com/homalg-project/CAP_project/pull/1367 now also displays a generic warning in such a case, even if one does not set `SetInfoLevel( InfoAttributes, 3 );`.
