### ISSUE TITLE
Get rid of IsEqualToIdentity/ZeroMorphism

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CategoricalTowers#322]
I would like to get rid of IsEqualToIdentityMorphism and IsEqualToZeroMorphism because I think they should more or less only be used in the context of natural transformations and they can easily be misinterpreted/misused. For example, IsEqualToZeroMorphism should probably be replaced by IsZeroForMorphisms here:
https://github.com/homalg-project/CategoricalTowers/blob/379e882895f0d61396e7ca41aa3fd90b1d3f620e/CategoryConstructor/gap/Tools.gi#L278-L282

@mohamed-barakat @kamalsaleh Could you look at the places where you use those two operations and check if they are actually used correctly?

**Comment by kamalsaleh** [comment]
The mentioned condition `IsEndomorphism( cat, delta_ij ) and not IsEqualToZeroMorphism( cat, alpha_ij )` could be modified to `IsEndomorphism( cat, delta_ij )` without any mathematical issues. The motivation was that this 'extra' condition ensures that Gauss-Algorithm will eventually be applied on a matrix with a lot of zeros. So, basically, It is a categorical implementation with side-tricks. I deliberately avoided using `IsZeroForMorphisms` as it is usually very expensive comparing to `IsEqualToZeroMorphism`.

So, you can just drop the condition or replace it with `IsEqualForMorphisms` but please never with `IsZeroForMorphisms` :-)

In HigherHomologicalAlgebra I don't use `IsEqualToIdentityMorphism` and `IsEqualToZeroMorphism`. The use of `IsEqualToIdentityMorphism` in _AlgebroidsFromDataTables.gi_ is also correct.

**Comment by zickgraf** [comment]
@kamalsaleh Thanks a lot for having a look and the explanation! I didn't expect `IsEqualToIdentityMorphism` and `IsEqualToZeroMorphism` to be used for performance optimizations at so many places. Then we can keep everything as it is.
