### ISSUE TITLE
Add weak kernels and cokernels to additive closures of Hom-finite algebroids

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/CategoricalTowers#85]
A draft might be found in https://github.com/kamalsaleh/Algebroids/blob/c706c84e77506f496f4ec7bcf1999cbee05129ef/gap/tmp.gi#L1-L69

**Comment by mohamed-barakat** [comment]
@kamalsaleh: I remember you have done something about this.

**Comment by kamalsaleh** [comment]
Yes, in algebroids from data tables, I am now adding weak kernels and cokernels using `BasisOfSolutionsOfHomogeneousLinearSystemInLinearCategory`; i.e., there is no need anymore to use Yoneda embedding and its inverse. For details see:
https://github.com/homalg-project/CategoricalTowers/blob/c6ceb78fd822013b5cae8517f48e752097efa5e4/Algebroids/gap/AlgebroidFromDataTables.gi#L1181-L1227

So, I think this issue could be closed.

**Comment by mohamed-barakat** [comment]
Excellent, thank you very much.
